"""Add currency to Project model and remove from Income/Expense

Revision ID: af122ca6cc16
Revises: b6c35cbda2b5
Create Date: 2024-06-24 21:43:38.212610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af122ca6cc16'
down_revision = 'b6c35cbda2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), nullable=False))

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
